/**
 * Skill Context Analysis Visualization
 * 
 * Shows the SkillContextObject generated by the LLM from aggregated SERP data.
 * Displays complexity score, prerequisite gaps, phases, and failure modes.
 */

export interface SkillContextObject {
  skill_name: string;
  complexity_score: number;
  prerequisite_gaps: string[];
  estimated_phases: string[];
  common_failure_modes: string[];
}

export interface SkillContextAnalysisProps {
  skillContext?: Partial<SkillContextObject>;
  isLoading?: boolean;
  skillName: string;
  complexity?: number;
}

export function SkillContextAnalysis({
  skillContext,
  isLoading = false,
  skillName,
  complexity = 0.65,
}: SkillContextAnalysisProps) {
  // Default context if not provided (shows what LLM would generate)
  const defaultContext: Partial<SkillContextObject> = {
    skill_name: skillName,
    complexity_score: complexity,
    prerequisite_gaps: [
      "Foundational theory",
      "Basic tooling",
      "Mathematical concepts",
    ],
    estimated_phases: ["Fundamentals", "Technique", "Application", "Mastery"],
    common_failure_modes: [
      "Inconsistent practice",
      "Tool overwhelm",
      "Plateau resistance",
    ],
  };

  const context = skillContext && skillContext.skill_name ? skillContext : defaultContext;

  return (
    <div
      style={{
        padding: "12px",
        backgroundColor: "rgba(11, 74, 43, 0.05)",
        borderRadius: "4px",
        border: "1px solid rgba(11, 74, 43, 0.2)",
        opacity: isLoading ? 0.6 : 1,
        transition: "opacity 0.3s",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", gap: "6px", marginBottom: "10px" }}>
        <span style={{ fontSize: "12px" }}>🤖</span>
        <p
          style={{
            margin: 0,
            fontWeight: "bold",
            color: "#0b4a2b",
            fontSize: "10px",
            textTransform: "uppercase",
          }}
        >
          LLM Analysis
          {isLoading && " (Generating...)"}
        </p>
      </div>

      <div style={{ display: "grid", gap: "10px", fontSize: "9px" }}>
        {/* Complexity Score */}
        <div>
          <div style={{ fontWeight: "bold", color: "#333", marginBottom: "4px" }}>
            Complexity: {((context.complexity_score || 0) * 100).toFixed(0)}%
          </div>
          <div
            style={{
              width: "100%",
              height: "6px",
              backgroundColor: "rgba(200, 200, 200, 0.2)",
              borderRadius: "3px",
              overflow: "hidden",
            }}
          >
            <div
              style={{
                height: "100%",
                width: `${(context.complexity_score || 0) * 100}%`,
                backgroundColor:
                  (context.complexity_score || 0) > 0.7 ? "#ff6b00" : "#0b4a2b",
                transition: "width 0.3s",
              }}
            />
          </div>
        </div>

        {/* Prerequisite Gaps */}
        {context.prerequisite_gaps && context.prerequisite_gaps.length > 0 && (
          <div>
            <div style={{ fontWeight: "bold", color: "#333", marginBottom: "4px" }}>
              📋 Prerequisite Gaps:
            </div>
            <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
              {context.prerequisite_gaps.map((gap, idx) => (
                <span
                  key={idx}
                  style={{
                    padding: "3px 6px",
                    backgroundColor: "rgba(255, 107, 0, 0.1)",
                    border: "1px solid rgba(255, 107, 0, 0.2)",
                    borderRadius: "3px",
                    fontSize: "8px",
                    color: "#666",
                  }}
                >
                  {gap}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Estimated Phases */}
        {context.estimated_phases && context.estimated_phases.length > 0 && (
          <div>
            <div style={{ fontWeight: "bold", color: "#333", marginBottom: "4px" }}>
              🗺️ Learning Phases:
            </div>
            <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
              {context.estimated_phases.map((phase, idx) => (
                <span
                  key={idx}
                  style={{
                    padding: "3px 6px",
                    backgroundColor: "rgba(11, 74, 43, 0.1)",
                    border: "1px solid rgba(11, 74, 43, 0.2)",
                    borderRadius: "3px",
                    fontSize: "8px",
                    color: "#0b4a2b",
                    fontWeight: "bold",
                  }}
                >
                  {phase}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Common Failure Modes */}
        {context.common_failure_modes && context.common_failure_modes.length > 0 && (
          <div>
            <div style={{ fontWeight: "bold", color: "#333", marginBottom: "4px" }}>
              ⚠️ Common Failures:
            </div>
            <div style={{ display: "flex", gap: "4px", flexWrap: "wrap" }}>
              {context.common_failure_modes.map((mode, idx) => (
                <span
                  key={idx}
                  style={{
                    padding: "3px 6px",
                    backgroundColor: "rgba(186, 0, 0, 0.1)",
                    border: "1px solid rgba(186, 0, 0, 0.2)",
                    borderRadius: "3px",
                    fontSize: "8px",
                    color: "#7a0000",
                  }}
                >
                  {mode}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      {isLoading && (
        <style>{`
          @keyframes pulse {
            0%, 100% { opacity: 1; }
            50% { opacity: 0.6; }
          }
          div { animation: pulse 2s infinite; }
        `}</style>
      )}
    </div>
  );
}
