"""add_missing_tables

Revision ID: 210020910165
Revises: 021
Create Date: 2026-04-25 15:52:38.267160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision = '210020910165'
down_revision = '021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_chunks',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('technique_id', sa.String(length=64), nullable=True),
    sa.Column('doc_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'source_url', 'chunk_index', name='uq_rag_chunks_skill_source_chunk')
    )
    op.create_table('rag_config',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), server_default=sa.text('512'), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), server_default=sa.text('64'), nullable=False),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_templates',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('complexity_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_skill_states',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.Numeric(precision=5), server_default=sa.text('1'), nullable=False),
    sa.Column('exposure_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('declarative_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('perceived_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('actual_level', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_bias', sa.Numeric(precision=6, scale=5), nullable=False),
    sa.Column('raw_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_research_objects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_research_objects_skill_id'), 'skill_research_objects', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_research_objects_user_id'), 'skill_research_objects', ['user_id'], unique=False)
    op.create_table('checkpoint_states',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('roadmap_id', sa.String(length=36), nullable=False),
    sa.Column('phase_slug', sa.String(length=64), nullable=False),
    sa.Column('checkpoint_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doubt_log',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('skill_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('chunks_used', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tip_log',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('technique_id', sa.String(length=64), nullable=False),
    sa.Column('failure_type', sa.String(length=64), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('tip', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('target_step', sa.String(length=64), nullable=True),
    sa.Column('chunks_used', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cognitive_profiles', sa.Column('assessment_metadata', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.alter_column('cognitive_profiles', 'cognitive_capacity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'attention_stability',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'learning_tolerance',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'motor_baseline',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'stress_resilience',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'time_constraint',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.drop_index('cognitive_profiles_user_id_idx', table_name='cognitive_profiles')
    op.drop_index('cognitive_profiles_version_idx', table_name='cognitive_profiles')
    op.create_index('cp_created_at_idx', 'cognitive_profiles', ['created_at'], unique=False)
    op.create_index('cp_user_id_idx', 'cognitive_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('cp_user_version_idx', 'cognitive_profiles', ['user_id', 'version'])
    op.drop_constraint('cognitive_profiles_user_id_fkey', 'cognitive_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'cognitive_profiles', 'users', ['user_id'], ['id'])
    op.add_column('evidence', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('evidence', sa.Column('artifact_key', sa.Text(), nullable=True))
    op.add_column('evidence', sa.Column('mime_type', sa.String(length=64), nullable=True))
    op.add_column('evidence', sa.Column('file_size_bytes', sa.BigInteger(), nullable=True))
    op.add_column('evidence', sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('evidence', 'checkpoint_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('evidence', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('evidence', 'artifact_url',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('evidence_checkpoint_id_idx', table_name='evidence')
    op.drop_index('evidence_session_id_idx', table_name='evidence')
    op.drop_constraint('evidence_session_id_fkey', 'evidence', type_='foreignkey')
    op.create_foreign_key(None, 'evidence', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'evidence', 'sessions', ['session_id'], ['id'])
    op.alter_column('learning_parameters', 'skill_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'difficulty_slope',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'phase_pacing',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'entry_phase_offset',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'repetition_intensity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'session_duration',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'micro_session_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'fatigue_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'break_frequency',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'technique_density',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'concurrent_technique_limit',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'abstraction_level',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'instruction_granularity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'checkpoint_frequency',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'checkpoint_rigidity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'error_tolerance_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'retry_limit',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'drill_depth',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'variation_intensity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'stress_exposure_rate',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'simulation_complexity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'feedback_detail_level',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'correction_delay_window',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'hint_activation_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'precision_requirement',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'speed_requirement',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'coordination_complexity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'adaptation_sensitivity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'risk_zone_trigger_level',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'regression_policy_strength',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'phase_transition_sensitivity',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'complexity_escalation_trigger',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'plateau_detection_threshold',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'stability_requirement_before_advance',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=5),
               existing_nullable=False)
    op.drop_index('learning_parameters_profile_id_idx', table_name='learning_parameters')
    op.drop_index('learning_parameters_skill_id_idx', table_name='learning_parameters')
    op.create_index('lp_profile_id_idx', 'learning_parameters', ['profile_id'], unique=False)
    op.create_unique_constraint('lp_profile_skill_idx', 'learning_parameters', ['profile_id', 'skill_id'])
    op.drop_constraint('learning_parameters_profile_id_fkey', 'learning_parameters', type_='foreignkey')
    op.create_foreign_key(None, 'learning_parameters', 'cognitive_profiles', ['profile_id'], ['id'])
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint('revoked_access_tokens_user_id_fkey', 'revoked_access_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'revoked_access_tokens', 'users', ['user_id'], ['id'])
    op.add_column('roadmaps', sa.Column('template_version', sa.Integer(), nullable=False))
    op.add_column('roadmaps', sa.Column('fingerprint', sa.String(length=64), nullable=False))
    op.add_column('roadmaps', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('roadmaps', 'skill_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('roadmaps', 'parameters_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('roadmaps_skill_id_idx', table_name='roadmaps')
    op.drop_index('roadmaps_status_idx', table_name='roadmaps')
    op.drop_index('roadmaps_user_id_idx', table_name='roadmaps')
    op.drop_constraint('roadmaps_user_id_fkey', 'roadmaps', type_='foreignkey')
    op.drop_constraint('roadmaps_parameters_id_fkey', 'roadmaps', type_='foreignkey')
    op.create_foreign_key(None, 'roadmaps', 'learning_parameters', ['parameters_id'], ['id'])
    op.create_foreign_key(None, 'roadmaps', 'users', ['user_id'], ['id'])
    op.add_column('sessions', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('sessions', sa.Column('attempt_number', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('sessions', sa.Column('protocol_steps_completed', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('sessions', sa.Column('failure_reason', sa.String(length=128), nullable=True))
    op.add_column('sessions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('sessions', 'phase',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('sessions', 'technique_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('sessions', 'metrics_captured',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sessions', 'protocol_violations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('sessions_roadmap_id_idx', table_name='sessions')
    op.drop_index('sessions_status_idx', table_name='sessions')
    op.drop_constraint('sessions_roadmap_id_fkey', 'sessions', type_='foreignkey')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sessions', 'roadmaps', ['roadmap_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_foreign_key('sessions_roadmap_id_fkey', 'sessions', 'roadmaps', ['roadmap_id'], ['id'], ondelete='CASCADE')
    op.create_index('sessions_status_idx', 'sessions', ['status'], unique=False)
    op.create_index('sessions_roadmap_id_idx', 'sessions', ['roadmap_id'], unique=False)
    op.alter_column('sessions', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sessions', 'protocol_violations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sessions', 'metrics_captured',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('sessions', 'technique_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('sessions', 'phase',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('sessions', 'created_at')
    op.drop_column('sessions', 'failure_reason')
    op.drop_column('sessions', 'protocol_steps_completed')
    op.drop_column('sessions', 'attempt_number')
    op.drop_column('sessions', 'user_id')
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.drop_constraint(None, 'roadmaps', type_='foreignkey')
    op.create_foreign_key('roadmaps_parameters_id_fkey', 'roadmaps', 'learning_parameters', ['parameters_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('roadmaps_user_id_fkey', 'roadmaps', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('roadmaps_user_id_idx', 'roadmaps', ['user_id'], unique=False)
    op.create_index('roadmaps_status_idx', 'roadmaps', ['status'], unique=False)
    op.create_index('roadmaps_skill_id_idx', 'roadmaps', ['skill_id'], unique=False)
    op.alter_column('roadmaps', 'parameters_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('roadmaps', 'skill_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('roadmaps', 'completed_at')
    op.drop_column('roadmaps', 'fingerprint')
    op.drop_column('roadmaps', 'template_version')
    op.drop_constraint(None, 'revoked_access_tokens', type_='foreignkey')
    op.create_foreign_key('revoked_access_tokens_user_id_fkey', 'revoked_access_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key('refresh_tokens_user_id_fkey', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'learning_parameters', type_='foreignkey')
    op.create_foreign_key('learning_parameters_profile_id_fkey', 'learning_parameters', 'cognitive_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('lp_profile_skill_idx', 'learning_parameters', type_='unique')
    op.drop_index('lp_profile_id_idx', table_name='learning_parameters')
    op.create_index('learning_parameters_skill_id_idx', 'learning_parameters', ['skill_id'], unique=False)
    op.create_index('learning_parameters_profile_id_idx', 'learning_parameters', ['profile_id'], unique=False)
    op.alter_column('learning_parameters', 'stability_requirement_before_advance',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'plateau_detection_threshold',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'complexity_escalation_trigger',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'phase_transition_sensitivity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'regression_policy_strength',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'risk_zone_trigger_level',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'adaptation_sensitivity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'coordination_complexity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'speed_requirement',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'precision_requirement',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'hint_activation_threshold',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'correction_delay_window',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'feedback_detail_level',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'simulation_complexity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'stress_exposure_rate',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'variation_intensity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'drill_depth',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'retry_limit',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'error_tolerance_threshold',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'checkpoint_rigidity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'checkpoint_frequency',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'instruction_granularity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'abstraction_level',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'concurrent_technique_limit',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'technique_density',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'break_frequency',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'fatigue_threshold',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'micro_session_enabled',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'session_duration',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'repetition_intensity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'entry_phase_offset',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'phase_pacing',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'difficulty_slope',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('learning_parameters', 'skill_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.drop_constraint(None, 'evidence', type_='foreignkey')
    op.create_foreign_key('evidence_session_id_fkey', 'evidence', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_index('evidence_session_id_idx', 'evidence', ['session_id'], unique=False)
    op.create_index('evidence_checkpoint_id_idx', 'evidence', ['checkpoint_id'], unique=False)
    op.alter_column('evidence', 'artifact_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)
    op.alter_column('evidence', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('evidence', 'checkpoint_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('evidence', 'validated_at')
    op.drop_column('evidence', 'file_size_bytes')
    op.drop_column('evidence', 'mime_type')
    op.drop_column('evidence', 'artifact_key')
    op.drop_column('evidence', 'user_id')
    op.drop_constraint(None, 'cognitive_profiles', type_='foreignkey')
    op.create_foreign_key('cognitive_profiles_user_id_fkey', 'cognitive_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('cp_user_version_idx', 'cognitive_profiles', type_='unique')
    op.drop_index('cp_user_id_idx', table_name='cognitive_profiles')
    op.drop_index('cp_created_at_idx', table_name='cognitive_profiles')
    op.create_index('cognitive_profiles_version_idx', 'cognitive_profiles', ['user_id', 'version'], unique=False)
    op.create_index('cognitive_profiles_user_id_idx', 'cognitive_profiles', ['user_id'], unique=False)
    op.alter_column('cognitive_profiles', 'time_constraint',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'stress_resilience',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'motor_baseline',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'learning_tolerance',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'attention_stability',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.alter_column('cognitive_profiles', 'cognitive_capacity',
               existing_type=sa.Numeric(precision=6, scale=5),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=False)
    op.drop_column('cognitive_profiles', 'assessment_metadata')
    op.drop_table('tip_log')
    op.drop_table('doubt_log')
    op.drop_table('checkpoint_states')
    op.drop_index(op.f('ix_skill_research_objects_user_id'), table_name='skill_research_objects')
    op.drop_index(op.f('ix_skill_research_objects_skill_id'), table_name='skill_research_objects')
    op.drop_table('skill_research_objects')
    op.drop_table('baseline_skill_states')
    op.drop_table('audit_log')
    op.drop_table('skill_templates')
    op.drop_table('rag_config')
    op.drop_table('rag_chunks')
    op.drop_table('jobs')
    # ### end Alembic commands ###
